// flow-typed signature: 3b4329e5cca0ad0e28e1fce62fcce348
// flow-typed version: <<STUB>>/v-mask_v^1.2.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'v-mask'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'v-mask' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'v-mask/__tests__/format.test' {
  declare module.exports: any;
}

declare module 'v-mask/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'v-mask/dist/format' {
  declare module.exports: any;
}

declare module 'v-mask/dist/index' {
  declare module.exports: any;
}

declare module 'v-mask/dist/utils/index' {
  declare module.exports: any;
}

declare module 'v-mask/src/format' {
  declare module.exports: any;
}

declare module 'v-mask/src/index' {
  declare module.exports: any;
}

declare module 'v-mask/src/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'v-mask/__tests__/format.test.js' {
  declare module.exports: $Exports<'v-mask/__tests__/format.test'>;
}
declare module 'v-mask/__tests__/index.test.js' {
  declare module.exports: $Exports<'v-mask/__tests__/index.test'>;
}
declare module 'v-mask/dist/format.js' {
  declare module.exports: $Exports<'v-mask/dist/format'>;
}
declare module 'v-mask/dist/index.js' {
  declare module.exports: $Exports<'v-mask/dist/index'>;
}
declare module 'v-mask/dist/utils/index.js' {
  declare module.exports: $Exports<'v-mask/dist/utils/index'>;
}
declare module 'v-mask/src/format.js' {
  declare module.exports: $Exports<'v-mask/src/format'>;
}
declare module 'v-mask/src/index.js' {
  declare module.exports: $Exports<'v-mask/src/index'>;
}
declare module 'v-mask/src/utils/index.js' {
  declare module.exports: $Exports<'v-mask/src/utils/index'>;
}
