// flow-typed signature: ecc2e87e69b26355ac040ffed72f3e82
// flow-typed version: <<STUB>>/vue-touch_v^2.0.0-beta.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-touch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-touch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-touch/dist/hammer-ssr' {
  declare module.exports: any;
}

declare module 'vue-touch/dist/vue-touch' {
  declare module.exports: any;
}

declare module 'vue-touch/dist/vue-touch.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-touch/dist/hammer-ssr.js' {
  declare module.exports: $Exports<'vue-touch/dist/hammer-ssr'>;
}
declare module 'vue-touch/dist/vue-touch.js' {
  declare module.exports: $Exports<'vue-touch/dist/vue-touch'>;
}
declare module 'vue-touch/dist/vue-touch.min.js' {
  declare module.exports: $Exports<'vue-touch/dist/vue-touch.min'>;
}
