// flow-typed signature: 718f0f7b97f038d2bd5ffaec15f3f21d
// flow-typed version: <<STUB>>/vue-outside-events_v^1.1.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-outside-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-outside-events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-outside-events/dist/vue-outside-events.min' {
  declare module.exports: any;
}

declare module 'vue-outside-events/docs/syntaxhighlighter' {
  declare module.exports: any;
}

declare module 'vue-outside-events/src/index' {
  declare module.exports: any;
}

declare module 'vue-outside-events/src/vue-outside-events' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-outside-events/dist/vue-outside-events.min.js' {
  declare module.exports: $Exports<'vue-outside-events/dist/vue-outside-events.min'>;
}
declare module 'vue-outside-events/docs/syntaxhighlighter.js' {
  declare module.exports: $Exports<'vue-outside-events/docs/syntaxhighlighter'>;
}
declare module 'vue-outside-events/src/index.js' {
  declare module.exports: $Exports<'vue-outside-events/src/index'>;
}
declare module 'vue-outside-events/src/vue-outside-events.js' {
  declare module.exports: $Exports<'vue-outside-events/src/vue-outside-events'>;
}
