// flow-typed signature: be360f1218fecd7f3ec97cf4bd17b680
// flow-typed version: <<STUB>>/vue-simple-breakpoints_v^1.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-simple-breakpoints'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-simple-breakpoints' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-simple-breakpoints/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-simple-breakpoints/dist/index.js' {
  declare module.exports: $Exports<'vue-simple-breakpoints/dist/index'>;
}
