// flow-typed signature: 17011d36f7d1945aac8934597062127e
// flow-typed version: <<STUB>>/vue-clipboard2_v0.0.6/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-clipboard2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-clipboard2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-clipboard2/browserify-me' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/dist/vue-clipboard' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/dist/vue-clipboard.min' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/build/build' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/build/check-versions' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/build/dev-client' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/build/dev-server' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/build/utils' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/build/vue-loader.conf' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/build/webpack.base.conf' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/build/webpack.dev.conf' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/build/webpack.prod.conf' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/config/dev.env' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/config/index' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/config/prod.env' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/sample-app/src/main' {
  declare module.exports: any;
}

declare module 'vue-clipboard2/vue-clipboard' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-clipboard2/browserify-me.js' {
  declare module.exports: $Exports<'vue-clipboard2/browserify-me'>;
}
declare module 'vue-clipboard2/dist/vue-clipboard.js' {
  declare module.exports: $Exports<'vue-clipboard2/dist/vue-clipboard'>;
}
declare module 'vue-clipboard2/dist/vue-clipboard.min.js' {
  declare module.exports: $Exports<'vue-clipboard2/dist/vue-clipboard.min'>;
}
declare module 'vue-clipboard2/sample-app/build/build.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/build/build'>;
}
declare module 'vue-clipboard2/sample-app/build/check-versions.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/build/check-versions'>;
}
declare module 'vue-clipboard2/sample-app/build/dev-client.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/build/dev-client'>;
}
declare module 'vue-clipboard2/sample-app/build/dev-server.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/build/dev-server'>;
}
declare module 'vue-clipboard2/sample-app/build/utils.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/build/utils'>;
}
declare module 'vue-clipboard2/sample-app/build/vue-loader.conf.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/build/vue-loader.conf'>;
}
declare module 'vue-clipboard2/sample-app/build/webpack.base.conf.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/build/webpack.base.conf'>;
}
declare module 'vue-clipboard2/sample-app/build/webpack.dev.conf.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/build/webpack.dev.conf'>;
}
declare module 'vue-clipboard2/sample-app/build/webpack.prod.conf.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/build/webpack.prod.conf'>;
}
declare module 'vue-clipboard2/sample-app/config/dev.env.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/config/dev.env'>;
}
declare module 'vue-clipboard2/sample-app/config/index.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/config/index'>;
}
declare module 'vue-clipboard2/sample-app/config/prod.env.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/config/prod.env'>;
}
declare module 'vue-clipboard2/sample-app/src/main.js' {
  declare module.exports: $Exports<'vue-clipboard2/sample-app/src/main'>;
}
declare module 'vue-clipboard2/vue-clipboard.js' {
  declare module.exports: $Exports<'vue-clipboard2/vue-clipboard'>;
}
