// flow-typed signature: 4c75b22ff82a9ed174182ffb858b942b
// flow-typed version: <<STUB>>/vuex-persistedstate_v^1.4.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuex-persistedstate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuex-persistedstate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuex-persistedstate/dist/vuex-persistedstate' {
  declare module.exports: any;
}

declare module 'vuex-persistedstate/dist/vuex-persistedstate.min' {
  declare module.exports: any;
}

declare module 'vuex-persistedstate/src/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuex-persistedstate/dist/vuex-persistedstate.js' {
  declare module.exports: $Exports<'vuex-persistedstate/dist/vuex-persistedstate'>;
}
declare module 'vuex-persistedstate/dist/vuex-persistedstate.min.js' {
  declare module.exports: $Exports<'vuex-persistedstate/dist/vuex-persistedstate.min'>;
}
declare module 'vuex-persistedstate/src/plugin.js' {
  declare module.exports: $Exports<'vuex-persistedstate/src/plugin'>;
}
